"use strict";
const fmt = (v, d = 3) => (v === null || v === undefined || !Number.isFinite(v) ? "n/a" : v.toFixed(d));
const SHORT = { "Seasonal Naive": "S. Naive", "ARIMA(1,1,1)": "ARIMA" };
const el = (tag, attrs = {}, text) => {
  const node = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => node.setAttribute(k, v));
  if (text !== undefined) node.textContent = text;
  return node;
};

function card(label, value, win) {
  const c = el("div", { class: "card" + (win ? " win" : "") });
  c.append(el("div", { class: "k" }, label), el("div", { class: "v" }, value));
  return c;
}

function render(r) {
  const win = r.winner;
  const w = r.evaluation.window;
  const cards = document.getElementById("cards");
  cards.append(
    card("Winner (avg MASE)", `${win.model} · ${fmt(win.average_mase)}`, true),
    card("vs seasonal naive", `${fmt(win.pct_better_than_seasonal_naive, 2)}% lower MASE`),
    card("Evaluation window", `${w.first_forecast_week} → ${w.last_forecast_week}`),
    card("Origins × commodities", `${r.evaluation.n_origins} × ${Object.keys(r.commodities).length}`)
  );

  const ranking = r.ranking_by_average_mase;
  const runnerUp = ranking[1];
  const gap = r.average[runnerUp].MASE - win.average_mase;
  document.getElementById("verdict").textContent =
    `${win.model} has the lowest average MASE (${fmt(win.average_mase)}), ` +
    `${fmt(win.mase_difference_vs_seasonal_naive)} lower than seasonal naive (${fmt(win.seasonal_naive_average_mase)}), ` +
    `an ${fmt(win.pct_better_than_seasonal_naive, 2)}% reduction. Its lead over ${runnerUp} is only ${fmt(gap, 4)} MASE.`;

  const avg = document.getElementById("avg-table");
  const head = el("tr");
  ["Rank", "Model", "MASE", "sMAPE (%)", "MAE"].forEach((h) => head.append(el("th", {}, h)));
  avg.append(head);
  ranking.forEach((m, i) => {
    const row = el("tr", m === win.model ? { class: "win" } : {});
    const a = r.average[m];
    [String(i + 1), m, fmt(a.MASE), fmt(a.sMAPE, 2), fmt(a.MAE, 2)].forEach((v) => row.append(el("td", {}, v)));
    avg.append(row);
  });
  avg.querySelectorAll("tr td:nth-child(2), tr th:nth-child(2)").forEach((c) => (c.style.textAlign = "left"));

  const ct = document.getElementById("commodity-table");
  const h2 = el("tr");
  h2.append(el("th", {}, "Commodity"));
  ranking.forEach((m) => h2.append(el("th", { title: m }, SHORT[m] || m)));
  ct.append(h2);
  Object.entries(r.per_commodity).forEach(([t, scores]) => {
    const row = el("tr");
    row.append(el("td", {}, r.commodities[t]));
    ranking.forEach((m) => row.append(el("td", r.commodity_winners[t] === m ? { class: "best" } : {}, fmt(scores[m].MASE))));
    ct.append(row);
  });

  const cs = document.getElementById("commodity");
  const ms = document.getElementById("model");
  Object.entries(r.commodities).forEach(([t, n]) => cs.append(el("option", { value: t }, n)));
  r.models.forEach((m) => ms.append(el("option", { value: m }, m)));
  ms.value = win.model;
  const draw = () => drawChart(r, cs.value, ms.value);
  cs.addEventListener("change", draw);
  ms.addEventListener("change", draw);
  window.addEventListener("resize", draw);
  draw();

  const method = document.getElementById("method");
  [
    `Data: ${r.data.frequency}, ${r.data.first_daily_date} to ${r.data.last_daily_date} daily closes.`,
    `Training starts ${w.training_start}; ${r.evaluation.n_origins} one-step forecasts from ${w.first_forecast_week} to ${w.last_forecast_week}.`,
    `${r.evaluation.method.charAt(0).toUpperCase()}${r.evaluation.method.slice(1)}.`,
    `Seasonal naive uses a ${r.evaluation.season_length}-week season; ARIMA order (${r.evaluation.arima_order.join(",")}); Prophet ${r.evaluation.prophet_version || "not installed"} with yearly seasonality.`,
    `MASE scale: ${r.evaluation.mase_scale}. Averages are the ${r.evaluation.average}.`,
  ].forEach((t) => method.append(el("li", {}, t)));

  document.getElementById("source").textContent =
    `Data source: Yahoo Finance (via yfinance), snapshot taken ${r.data.snapshot_date} and committed as ${r.data.snapshot_file}. ` +
    `Results generated by ${r.generated_by}. Not investment advice.`;
}

function drawChart(r, ticker, model) {
  const block = r.predictions[ticker];
  const box = document.getElementById("chart");
  const width = Math.max(280, Math.min(box.clientWidth || 800, 1060));
  const height = width < 500 ? 260 : 360;
  const pad = { l: width < 500 ? 44 : 60, r: 12, t: 12, b: 30 };
  const series = [block.actual, block.forecasts[model], block.forecasts["Seasonal Naive"]];
  const all = series.flat();
  let lo = Math.min(...all), hi = Math.max(...all);
  const span = hi - lo || 1; lo -= span * 0.05; hi += span * 0.05;
  const n = block.dates.length;
  const x = (i) => pad.l + (i / (n - 1)) * (width - pad.l - pad.r);
  const y = (v) => pad.t + (1 - (v - lo) / (hi - lo)) * (height - pad.t - pad.b);
  const path = (vals) => vals.map((v, i) => `${i ? "L" : "M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join("");
  const ns = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(ns, "svg");
  svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
  const add = (tag, attrs, text) => {
    const node = document.createElementNS(ns, tag);
    Object.entries(attrs).forEach(([k, v]) => node.setAttribute(k, v));
    if (text !== undefined) node.textContent = text;
    svg.append(node);
  };
  for (let k = 0; k <= 4; k++) {
    const v = lo + ((hi - lo) * k) / 4;
    add("line", { x1: pad.l, x2: width - pad.r, y1: y(v), y2: y(v), stroke: "#1F2937" });
    add("text", { x: pad.l - 6, y: y(v) + 4, fill: "#9CA3AF", "font-size": 11, "text-anchor": "end" }, v.toFixed(v < 10 ? 2 : 0));
  }
  const ticks = width < 500 ? 3 : 6;
  for (let k = 0; k <= ticks; k++) {
    const i = Math.round(((n - 1) * k) / ticks);
    add("text", { x: x(i), y: height - 8, fill: "#9CA3AF", "font-size": 11, "text-anchor": k === 0 ? "start" : k === ticks ? "end" : "middle" }, block.dates[i].slice(0, 7));
  }
  add("path", { d: path(series[2]), fill: "none", stroke: "#6B7280", "stroke-width": 1.4, "stroke-dasharray": "4 3" });
  add("path", { d: path(series[0]), fill: "none", stroke: "#E5E7EB", "stroke-width": 1.8 });
  add("path", { d: path(series[1]), fill: "none", stroke: "#10B981", "stroke-width": 2 });
  box.replaceChildren(svg);
  document.getElementById("legend-model").textContent = model;
  const s = r.per_commodity[ticker][model];
  document.getElementById("chart-stats").textContent =
    `${block.name} · ${model}: MASE ${fmt(s.MASE)}, sMAPE ${fmt(s.sMAPE, 2)}%, MAE ${fmt(s.MAE, 3)}, ` +
    `MAPE ${s.MAPE === null ? "n/a" : fmt(s.MAPE, 2) + "%"}, directional accuracy ${s.DirectionalAccuracy === null ? "n/a" : fmt(s.DirectionalAccuracy * 100, 1) + "%"}.`;
}

fetch("leaderboard.json")
  .then((res) => { if (!res.ok) throw new Error(`HTTP ${res.status}`); return res.json(); })
  .then(render)
  .catch((err) => {
    document.getElementById("verdict").textContent = `Could not load leaderboard.json (${err.message}).`;
  });
